name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: imohit14/multiagent-app
  RESOURCE_GROUP: test
  CONTAINER_APP_NAME: multiagentapp

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # -----------------------------------
      # Checkout Repository
      # -----------------------------------

      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------------
      # Docker Hub Login
      # -----------------------------------

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------------
      # Build Docker Image
      # -----------------------------------

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      # -----------------------------------
      # Push Docker Images
      # -----------------------------------

      - name: Push Docker Images
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      # -----------------------------------
      # Azure Login
      # -----------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # -----------------------------------
      # Install Azure Container Apps Extension
      # -----------------------------------

      - name: Install Container Apps Extension
        run: |
          az extension add --name containerapp --upgrade

      # -----------------------------------
      # Deploy Latest Image
      # -----------------------------------

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $IMAGE_NAME:latest